// packages/app-react/pages/index.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faFlagCheckered } from "@fortawesome/free-solid-svg-icons"
import Head from "next/head"
import styled from "styled-components"
import StepCard from "../components/StepCard"
import Arrow, { ARROW_HEAD_WIDTH } from "../components/Arrow"
import { GetServerSideProps, InferGetServerSidePropsType } from "next"
import { Scenario } from "@iaf/api/build/types"

export const getServerSideProps: GetServerSideProps<Scenario> = async () => {
  const res = await fetch(`http://localhost:8080/scenario`)
  const { name, steps } = (await res.json()) as Scenario
  return { props: { name, steps } }
}

export default function Home({
  name,
  steps,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>{name}</h1>
        <p>Total steps: {steps.length}</p>
        <Wrapper>
          {steps.map((step, idx) => (
            <StepCardWrapper key={step.id}>
              <StepCard step={step} stepNumber={idx + 1} />
              <ArrowWrapper>
                <Arrow />
              </ArrowWrapper>
            </StepCardWrapper>
          ))}
          <FinishCardWrapper>
            <FinishCard>
              <FontAwesomeIcon icon={faFlagCheckered} />
              Finish
            </FinishCard>
          </FinishCardWrapper>
        </Wrapper>
      </Main>
    </>
  )
}

const Main = styled.main`
  padding: 2.5rem 5rem;
`
const Wrapper = styled.div`
  display: flex;
  flex-wrap: wrap;
`
const ARROW_WIDTH = "3.25rem"
const StepCardWrapper = styled.div`
  position: relative;
  margin: 1.25rem calc(${ARROW_WIDTH} - ${ARROW_HEAD_WIDTH}) 0 0;
  display: flex;
`
const ArrowWrapper = styled.div`
  position: absolute;
  right: 0;
  transform: translate(100%, -50%);
  top: 50%;
  width: ${ARROW_WIDTH};
`
const FinishCardWrapper = styled(StepCardWrapper)`
  display: flex;
  align-items: center;
`
const FinishCard = styled.div`
  background: #ffffff;
  padding: 0.5rem 0.75rem;
  border-radius: 0.25rem;
  svg {
    margin-right: 0.25rem;
  }
`

// packages/app-vue/pages/index.vue
<template>
  <main class="main">
    <h1>{{ name }}</h1>
    <p>Total steps: {{ steps.length }}</p>
    <div class="cards-wrapper">
      <div
        v-for="(step, idx) in steps"
        :key="step.id"
        class="step-card-wrapper"
      >
        <StepCard :step="step" :step-number="idx + 1" />
        <div class="arrow-wrapper">
          <Arrow />
        </div>
      </div>
      <div class="step-card-wrapper finish-card-wrapper">
        <div class="finish-card">
          <font-awesome-icon icon="flag-checkered" />
          Finish
        </div>
      </div>
    </div>
  </main>
</template>

<script lang="ts">
import Vue from "vue"
import { library } from "@fortawesome/fontawesome-svg-core"
import { faFlagCheckered } from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
import { Scenario } from "@iaf/api/build/types"

library.add(faFlagCheckered)

Vue.component("font-awesome-icon", FontAwesomeIcon)

export default {
  async asyncData() {
    const res = await fetch(`http://localhost:8080/scenario`)
    const { name, steps } = (await res.json()) as Scenario
    return { name, steps }
  },
}
</script>

<style scoped>
.main {
  padding: 2.5rem 5rem;
}
.cards-wrapper {
  display: flex;
  flex-wrap: wrap;
}
.step-card-wrapper {
  position: relative;
  margin: 1.25rem calc(3.25rem - 0.75rem) 0 0;
  display: flex;
}
.arrow-wrapper {
  position: absolute;
  right: 0;
  transform: translate(100%, -50%);
  top: 50%;
  width: 3.25rem;
}
.finish-card-wrapper {
  display: flex;
  align-items: center;
}
.finish-card {
  background: #fff;
  padding: 0.5rem 0.75rem;
  border-radius: 0.25rem;
}
svg {
  margin-right: 0.25rem;
}
</style>
